const SCHOOL_WIKI_VERSION = "2026-05-22-school-import-3";

const FEATURED_TOPICS = [
  "Antimatter",
  "Quantum States",
  "Pokemon",
  "The Red Baron",
  "Project Hail Mary",
  "Green Day",
  "Magic the Gathering",
  "How to make a McDonald's cheeseburger",
];

const IMPORTED_ARTICLES = [
  {
    title: "Antimatter",
    author: "Miller Kircher",
    topic: "Science",
    body: "Antimatter was created at the start of the universe along with matter. The mystery is why the universe has much more matter than antimatter today. When antimatter and matter collide, they annihilate into energy. CERN and other researchers study whether antimatter behaves like regular matter, including how it responds to gravity.\n\nSources:\nhttps://en.wikipedia.org/wiki/Antimatter\nhttps://home.cern/science/physics/antimatter/\n\nSee:\nQuantum States",
  },
  {
    title: "ANTS",
    author: "Imported class article",
    topic: "Animals",
    body: "Ants are insects in the family Formicidae. Their societies are organized around queens, workers, soldiers, and males. Ants communicate mostly through pheromones, build complex nests, farm fungi, herd aphids, disperse seeds, aerate soil, and fight territorial wars with other colonies.\n\nKey sections imported from the original tab: taxonomic classification, anatomy, caste system, chemical communication, colony lifecycle, diet and mutualisms, nest architecture, warfare, and ecological impact.\n\nSources used section needed.",
  },
  {
    title: "Axolotl",
    author: "Miller Kircher",
    topic: "Animals",
    body: "The axolotl, Ambystoma mexicanum, is a critically endangered mole salamander naturally found in Lake Xochimilco. Axolotls reach maturity without undergoing normal metamorphosis. They are famous for regeneration: injured limbs and even parts of the brain can grow back. Their name is connected to Xolotl, a salamander god in mythology.\n\nSources:\nhttps://en.wikipedia.org/wiki/Xolotl\nhttps://en.wikipedia.org/wiki/Axolotl",
  },
  {
    title: "Black Hole",
    author: "Imported class article",
    topic: "Space",
    body: "Black holes are regions of spacetime where gravity is so strong that not even light can escape. The original tab covered dark stars, Einstein's general relativity, Schwarzschild's solution, event horizons, singularities, photon spheres, ergospheres, accretion disks, gravitational waves, the Event Horizon Telescope, Hawking radiation, the information paradox, and how black holes affect galaxy evolution.\n\nSources used section needed.",
  },
  {
    title: "Blindness Cure",
    author: "Roshan Zieminski",
    topic: "Science",
    body: "Some experimental technology attempts to restore a form of sight by connecting sensors to implants near the visual cortex. A sensor can detect light patterns and stimulate implanted diodes in a matching pattern, giving the user a limited visual image. The system is not perfect, but it can provide a sense of vision.\n\nSources used section needed.",
  },
  {
    title: "Chess",
    author: "Raleigh",
    topic: "Games",
    body: "Chess is a board game where white moves first and each player moves one piece per turn. The original tab explains the pawn, knight, bishop, rook, castling, en passant, promotion, and basic capturing rules. Pawns move forward and capture diagonally, knights move in an L shape, bishops move diagonally, and rooks move in straight lines.\n\nSources used section needed.",
  },
  {
    title: "Coleoids",
    author: "Keiden",
    topic: "Animals",
    body: "Coleoids are a subclass of cephalopods consisting of Octopodiformes and Decopodiformes. The tab starts sections for octopods, Cirrata, Incirrata, and decopods. Cirrate octopuses include flapjack devilfish and dumbo octopuses.\n\nSources used section needed.",
  },
  {
    title: "Dance",
    author: "Willa",
    topic: "Art",
    body: "Dance has existed for thousands of years across many cultures. It is also a strong workout. Styles include ballet, hip-hop, jazz, pointe, tap, modern, lyrical, contemporary, and breakdancing. Pointe is a classical technique where dancers support their body weight on the tips of reinforced pointe shoes after strengthening their feet.\n\nSources used section needed.",
  },
  {
    title: "Dogs",
    author: "Imported class article",
    topic: "Animals",
    body: "Dogs, Canis lupus familiaris, have one of the strongest cross-species bonds with humans. The original tab covered domestication from ancient wolves, artificial selection, breed diversity, scent and hearing abilities, social cognition, attachment, health benefits, service roles, therapy dogs, conservation work, and responsible ownership.\n\nSources used section needed.",
  },
  {
    title: "Enceladus",
    author: "Roshan Zieminski",
    topic: "Space",
    body: "Enceladus is an icy moon of Saturn and a possible candidate for extraterrestrial life. It has an ice crust, a subsurface ocean, and jets near the south pole that blast water into space. One theory is that the heated water comes from underwater volcanic activity, which matters because life on Earth may have begun near underwater volcanoes.\n\nSources used section needed.",
  },
  {
    title: "F1 Racing",
    author: "Talon and Jack",
    topic: "Sports",
    body: "The F1 tab traces Formula 1 from the first official championship race at Silverstone in 1950 through front-engine cars, mid-engine designs, wings, ground effect, turbo engines, Prost vs. Senna, carbon fiber, Imola 1994 safety reforms, Ferrari dominance, hybrid power units, Liberty Media, cost caps, modern ground effect, and future active aero.\n\nSources used section needed.",
  },
  {
    title: "Felidae",
    author: "Imported class article",
    topic: "Animals",
    body: "Felidae is the mammal family commonly known as cats. Members are carnivores with traits like retractable claws, night vision, and sensitive hearing. The tab starts sections for Pantherinae, Felinae, and Acinonyx, including cheetahs.\n\nSources used section needed.",
  },
  {
    title: "Ferrets",
    author: "Delia",
    topic: "Animals",
    body: "Ferrets are small carnivores in the weasel family. They were domesticated from European relatives and are energetic, intelligent, mischievous, and sometimes aggressive. Their diet needs high protein and animal fat with very low carbohydrates.\n\nSources used section needed.",
  },
  {
    title: "Green Day",
    author: "Esai",
    topic: "Music",
    body: "Green Day is an American punk rock band formed in 1987 in Rodeo, California. The main trio is Billie Joe Armstrong, Mike Dirnt, and Tre Cool. They became famous with Dookie in 1994 and reinforced their status with American Idiot in 2004.\n\nSources:\nWikipedia.org",
  },
  {
    title: "How to make McDonald's chicken nuggets",
    author: "Talon",
    topic: "Food",
    body: "This recipe uses ground chicken, egg, salt, pepper, cornstarch, flour, onion powder, garlic powder, cold club soda, and frying oil. Blend the chicken into a paste, shape nuggets, coat with cornstarch, freeze briefly, dip in tempura batter, fry at 350F, and cook to 165F internal temperature.\n\nSources used section needed.",
  },
  {
    title: "How to make a McDonald's cheeseburger",
    author: "Louie",
    topic: "Food",
    body: "The cheeseburger tab explains how to make a homemade copycat cheeseburger with thin 80/20 beef patties, buns, ketchup, mustard, minced onions, pickles, and American cheese. The patty mix uses ground beef, bread crumbs, egg, salt, and pepper. The original pasted recipe also included prep/cook times and assembly steps.\n\nSources used section needed.",
  },
  {
    title: "Io",
    author: "Roshan Zieminski",
    topic: "Space",
    body: "Io is one of Jupiter's moons and one of the most volcanically active worlds known. Its volcanoes are powered by tidal forces from Jupiter and its elliptical orbit, which stretch and compress the moon. NASA's Juno mission has studied Io.\n\nFor more information:\nhttps://science.nasa.gov/jupiter/jupiter-moons/io/",
  },
  {
    title: "Magic the Gathering",
    author: "Jonah Staub",
    topic: "Games",
    body: "Magic: The Gathering is a tabletop and digital collectible card game created by Richard Garfield and released by Wizards of the Coast in 1993. Players represent dueling Planeswalkers and use cards for lands, creatures, spells, artifacts, enchantments, planeswalkers, and battles. Formats include constructed and limited.\n\nSources:\nWikipedia",
  },
  {
    title: "Mango",
    author: "Jack and Talon",
    topic: "Food",
    body: "The mango tab covers Mangifera indica, a tropical drupe in the Anacardiaceae family. It discusses origins in the Indian subcontinent, cultural importance, cultivation, varieties like Alphonso, Tommy Atkins, Kent, Ataulfo, and Carabao, global production, nutrition, culinary uses, genetics, pests, disease, climate vulnerability, and the US mango industry.\n\nSources used section needed.",
  },
  {
    title: "McDonald's",
    author: "Imported class article",
    topic: "Food",
    body: "McDonald's is a fast food chain found around the world. It is famous for burgers like the Big Mac and is one of the most popular fast food chains in the world.\n\nSources used section needed.",
  },
  {
    title: "Phillies",
    author: "Imported class article",
    topic: "Sports",
    body: "The Philadelphia Phillies are an MLB team. They travel around the United States and Canada to play baseball against other teams. The original tab points readers to the official MLB rulebook.\n\nSources used section needed.",
  },
  {
    title: "Pokemon",
    author: "Auggie Hamilton",
    topic: "Games",
    body: "Pokemon is one of the most popular trading card games and media franchises in the world. The tab mentions the anime, video games, world championships, over 1,000 Pokemon forms, and websites for collectors, buying cards, news, and play.\n\nLinks from tab:\nhttps://www.tcgcollector.com/dashboard/intl\nhttps://www.tcgplayer.com/search/all/product?q=pokemon&view=grid\nhttps://www.pokemon.com\nhttps://limitlesstcg.com\nhttps://www.pokebeach.com",
  },
  {
    title: "Polls on Random Stuff",
    author: "Mari and Maya",
    topic: "Other",
    body: "A class poll page for random topics. The imported poll asks people to put their name under team summer or team winter.\n\nSources used section needed.",
  },
  {
    title: "Project Hail Mary",
    author: "Connor",
    topic: "Books",
    body: "Project Hail Mary is about Ryland Grace, a science teacher who wakes up in space with amnesia. He discovers he is on a mission related to Astrophage, an organism dimming stars. The story follows his memory, the mission, and contact with an alien ally.\n\nSources used section needed.",
  },
  {
    title: "Quantum States",
    author: "Roshan Ziemenski",
    topic: "Science",
    body: "Quantum theory explores strange particle behavior. The tab describes superposition, where an unobserved particle may not have one definite state, and cosmic radiation near black holes, where particle pairs can lead to radiation and black hole mass loss.\n\nSources:\nhttps://en.wikipedia.org/wiki/Quantum_state\n\nSee:\nAntimatter\nDark energy",
  },
  {
    title: "Rappers",
    author: "Wamy and classmates",
    topic: "Music",
    body: "A class list of favorite rappers and rap groups, including E-40, 2Pac, MF DOOM, Snoop Dogg, Outkast, Fugees, Jay-Z, Mac Dre, Nas, Eminem, Dr. Dre, N.W.A., A Tribe Called Quest, Sugar Hill Gang, Drake, and others.\n\nSources used section needed.",
  },
  {
    title: "Snails",
    author: "Lyona Davis",
    topic: "Animals",
    body: "A snail is a shelled gastropod. The term can apply to land snails, sea snails, and freshwater snails. Some aquatic snails can live in freshwater or salt water. Water snails lay eggs through a reproductive organ under their shell and often coat eggs in protective jelly-like slime.\n\nSuggested sources from tab: University of Florida Freshwater Snails of Florida ID Guide; Montana Field Guide for Aquatic Snails.",
  },
  {
    title: "Space Sounds",
    author: "Roshan Zieminski",
    topic: "Space",
    body: "Space is not completely silent in the sense that many objects create waves that scientists can convert into sound. The tab mentions sounds detected from Earth, the Sun, the Moon, planets, moons, supernovas, kilonovas, pulsars, magnetars, black holes, white holes, and stars.\n\nFor more information: ESA - Sounds from space",
  },
  {
    title: "Spindrift",
    author: "Wamy",
    topic: "Food",
    body: "Spindrift is described as the best drink because it is cold, good, better than Waterloo, made with juice and water, and very good.\n\nSources used section needed.",
  },
  {
    title: "Sports People",
    author: "Noah Tse and Emmett Watts",
    topic: "Sports",
    body: "This page lists famous athletes across sports, including LeBron James, Stephen Curry, Shohei Ohtani, Tom Brady, Lionel Messi, Cristiano Ronaldo, Serena Williams, Simone Biles, and others. It starts a section on LeBron James and his impact on basketball.\n\nSources used section needed.",
  },
  {
    title: "Stock Market",
    author: "Imported class article",
    topic: "History",
    body: "The stock market is where people buy and sell pieces of companies. Investors can make or lose money. Large crashes can harm the global economy, with the Great Depression listed as an example.\n\nSources used section needed.",
  },
  {
    title: "Stuff",
    author: "Louie O'Neill",
    topic: "Language",
    body: "This article explains the word 'stuff' as one of English's most flexible placeholder words. It covers its Old French and Old High German roots, medieval meanings, later uses for materials and supplies, Shakespeare's 'sterner stuff,' modern idioms like 'know one's stuff' and 'the right stuff,' and its use as a noun and verb.\n\nSources used section needed.",
  },
  {
    title: "Dancing Plague of 1518",
    author: "Imported class article",
    topic: "History",
    body: "The dancing plague of 1518 began in Strasbourg when Frau Troffea reportedly started dancing uncontrollably in the street. Others joined, and by August between 50 and 400 people were said to be affected. Some dancers collapsed.\n\nSources used section needed.",
  },
  {
    title: "History of Minecraft",
    author: "Aylan",
    topic: "Games",
    body: "Minecraft is a popular game released in 2011. The tab mentions early access, early players, rapid popularity, and awards.\n\nSources used section needed.",
  },
  {
    title: "History of YessirPlayz",
    author: "Wyatt Keller Mih, narrated by Derp",
    topic: "Games",
    body: "This article investigates the YouTuber YessirPlayz, a Roblox creator who started in 2020, grew during 2025 with frequent shorts, focused on Grow a Garden videos, then appeared to pause or vanish around April 2026. The article describes searching for old videos and trying to piece together the creator's history.\n\nSources used section needed.",
  },
  {
    title: "Hobbit",
    author: "Imported class article",
    topic: "Books",
    body: "The Hobbit is a book by J.R.R. Tolkien about Bilbo Baggins from Hobbiton. He goes on a journey involving the dragon Smaug.\n\nSources used section needed.",
  },
  {
    title: "Paralysis Plague",
    author: "Roshan Zieminski",
    topic: "Science",
    body: "This article describes a strange historical plague that supposedly causes long-term paralysis and a coma-like state before a brief final period of awareness. It needs sources and verification.\n\nSources used section needed.",
  },
  {
    title: "Red Baron",
    author: "Aylan Sisalem",
    topic: "History",
    body: "The Red Baron was a German World War I pilot credited with 80 aerial victories. The article describes his final dogfight in 1918, the debate over who shot him down, museum pieces from his plane, and the Red Baron in Snoopy comics.\n\nSources used section needed.",
  },
  {
    title: "Tritera",
    author: "Jonah Staub",
    topic: "Games",
    body: "Tritera is a Dungeons & Dragons campaign setting about evolved animal-based species. It was created by Turk, Wiggledy da Worm, and Gorthak after their homeworld was destroyed. Major continents include Gobo, Icktheon, and Ignia. The setting includes Gobblers, Wormfolk, Rocketfire Monkeys, Magma Dragons, custom backgrounds, magic, gear, and monsters.\n\nSources used section needed.",
  },
  {
    title: "Underwater Bees",
    author: "Theo Jacob",
    topic: "Animals",
    body: "Queen bumblebees can survive about a week underwater while hibernating. The discovery happened accidentally when scientist Sabrina Rondeau found flooded refrigerated tubes with living hibernating queens. Their metabolism slowed, and they took days to move again after being removed.\n\nSources used section needed.",
  },
  {
    title: "World War II",
    author: "Aylan",
    topic: "History",
    body: "This tab begins with Pearl Harbor and the Doolittle Raid. It mentions planes sent to bomb Tokyo in 1942, some crews landing or crashing, one plane landing in Russia because of fuel, and the crews being honored.\n\nSources used section needed.",
  },
  {
    title: "Mythical Animals and Items",
    author: "Alex",
    topic: "Mythology",
    body: "This page starts a topic about mythical animals and magic items. It mentions jade as a protective stone associated with luck and centaurs as half-human, half-horse beings who may be hunters, warriors, or wise figures.\n\nSources used section needed.",
  },
];

window.SCHOOL_WIKI_VERSION = SCHOOL_WIKI_VERSION;
window.FEATURED_TOPICS = FEATURED_TOPICS;
window.IMPORTED_ARTICLES = IMPORTED_ARTICLES;
